language: c

before_install:
    - bash install.sh

script:
    - bash build.sh

notifications:
    on_failure: change
    on_success: change

cache:
    directories:
        - .cache
    apt: true

env:
    - OPENRCT2_CMAKE_OPTS="-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"

sudo: required
os: osx
osx_image: xcode7
